baseURL = 'https://jadarma.github.io/blog'
languageCode = 'en-us'
title = "Jadarma's Blog"
copyright = "© 2024 Dan Cîmpianu"

# No need for a dedicated page for each taxonomy, they are inlined in the filters.
disableKinds = [ 'taxonomy' ]

# Set the number of posts per filter page.
[pagination]
pagerSize = 10

# Adjust URL structure.
[permalinks]
    [permalinks.page]
        posts = '/posts/:year/:month/:slug'
    [permalinks.term]
        series = '/series/:slug'
        tags = '/filter/tag/:slug'
        category = '/filter/category/:slug'

[taxonomies]
category = 'category'
tag = 'tags'
series = 'series'

# Enable RSS for the main index only.
[outputs]
home = ['html', 'rss']
section = ['html']
taxonomy = ['html']
term = ['html']

[markup.highlight]
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
tabWidth = 4
