baseURL = 'https://jadarma.github.io/blog'
languageCode = 'en-us'
title = "Jadarma's Blog"

# No need for a dedicated page for each taxonomy, they are inlined in the filters.
disableKinds = [ 'taxonomy' ]

# Adjust URL structure.
[permalinks]
    [permalinks.page]
        posts = '/posts/:year/:month/:slug'
    [permalinks.term]
        series = '/series/:slug'
        tags = '/filter/tag/:slug'
        category = '/filter/category/:slug'

[taxonomies]
category = 'category'
tag = 'tags'
series = 'series'

[markup.highlight]
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
tabWidth = 4
